main.py
from flask import Flask, render_template
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

"""
Rota de clientes

- /clientes/ (GET) - Listar os clientes
- /clientes/ (POST) - inserir clients no servidor
- /clientes/new (GET) - renderizar formulario para criar um cliente
- /clientes/<id> (GET) - obter os dados de um clientes
- /clientes/<id>/edit (GET) - renderizar um formalulario para editar um cliente
- /clientes/<id>/update (PUT) - atualizar os dados do cliente
- /clientes/<id>/delete (DELETE) - delata o registro do usuario

"""

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route("/")
def lista_clientes():
    # Listar os clientes
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    # inserir clientes no servidor
    
    data = request.json

    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }

    CLIENTES.append(novo_usuario)


    return render_template('item_cliente.html', clientes=novo_usuario)

@cliente_route.route('/new')
def form_cliente():
 # renderizar formulario para criar um cliente
   return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    # exibir detalhes do cliente 
    return render_template('detalhe_cliente.html')

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    # formulario para editar um cliente
    return render_template('form_edit_cliente.html')

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def update_cliente(cliente_id):
    # atualizar os dados cliente
    pass

@cliente_route.route('/<int:clinte_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    # deletar um cliente
    pass

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" 
    action="{{ url_for('cliente.inserir_cliente') }}" 
    method="POST"
    c-append="#lista_clientes">


    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome">
    </div>

    <div class="mb-3">
      <label class="form-label">E-mail</label>
      <input type="text" class="form-control" name="email">
    </div>
    
    <button type="submit" class="btn btn-primary">Adicionar Cliente</button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Teste</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel=stylesheet href="{{ url_for('static', filename='css/app.css')}}">
  </head>
  <body>

    <div class="container">
      <h1>Gestão de clientes</h1>

      <!-- Formulário de clientes -->
      <div c-container="{{ url_for('cliente.form_cliente') }}"></div>
      <hr>
      <!-- Lista de Clientes-->
      <h2>Lista de clientes</h2>
      <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr>
    <th scope="row"> {{ clientes.id }}</th>
    <td>{{ clientes.nome }}</td>
    <td>{{ clientes.email }}</td>
    <td>
        <button class="btn btn-primary">Editar</button>
        <button class="btn btn-danger">Deletar</button>
    </td>
  </tr>

templates/lista_clientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.12"></script>
    <title>Clientes</title>
</head>
<body>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        
        <tbody id="lista_clientes">

            {% for clientes in clientes %}
                {% include 'item_cliente.html' %}
            {% endfor %}

        </tbody>
      </table>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>             
</body>
</html>